# syntax = edrevo/dockerfile-plus
# Docker/Kubernetes file for running the image API

FROM node:alpine

INCLUDE+ Dockerfile.base

RUN apk add --no-cache redis
RUN service redis start

USER esmBot

EXPOSE 8080 8081

ENTRYPOINT ["node", "api/index.js"]