name: Build Test

permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release

jobs:
  build_natives:
    strategy:
      matrix:
        platform:
          - os: ubuntu-24.04
            key: linux-amd64
          - os: ubuntu-24.04-arm
            key: linux-aarch64
          - os: macos-15
            key: macos-aarch64
    name: Build natives (${{matrix.platform.key}})
    runs-on: ${{matrix.platform.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271  # v6
      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 22.13
          cache: pnpm

      - name: Install dependencies (Linux)
        if: contains(matrix.platform.key, 'linux')
        run: sudo apt update && sudo apt install -y cmake libvips-dev libmagick++-dev libzxing-dev
      - name: Install dependencies (macOS)
        if: contains(matrix.platform.key, 'macos')
        run: brew install imagemagick vips

      - name: Build
        run: pnpm install --frozen-lockfile && pnpm run build
      - name: Upload natives
        uses: actions/upload-artifact@v7
        with:
          name: ${{matrix.platform.key}}
          path: build/Release/esmbmedia.node
